### ISSUE TITLE
Telegram link

### ISSUE THREAD

**Issue by punk8** [Honeypot-Finance/honeypot_frontend_v2#12]
The Telegram redirect link has an issue.

**Comment by rabbitblood** [comment]
input was in the wrong format, added form validator

**Comment by punk8** [comment]
![image](https://github.com/user-attachments/assets/f294bf35-0681-4b97-aff7-e9944c501992)
Is it possible to support direct input of ‘@test’ to automatically convert it to https://t.me/test?

**Comment by rabbitblood** [comment]
input now with @username will be convert to link
