### ISSUE TITLE
改公告让用户知道可以迁移beta2合约到beta3

### ISSUE THREAD

**Issue by rabbitblood** [Honeypot-Finance/honeypot_frontend_v2#132]

**Comment by rabbitblood** [comment]
![51561728178574_ pic](https://github.com/user-attachments/assets/b014c8df-6e20-497a-9689-001006a02c46)

**Comment by zongzheng123** [comment]
This should be ready done

**Comment by rabbitblood** [comment]
![1729025399493](https://github.com/user-attachments/assets/b96b4d64-1abd-480a-ae16-348ea3e4dbb5)
