### ISSUE TITLE
添加代币的价格展示以及价格影响

### ISSUE THREAD

**Issue by punk8** [Honeypot-Finance/honeypot_frontend_v2#141]
![image](https://github.com/user-attachments/assets/fc549087-528a-4e41-9d48-238145c26c87)
![image](https://github.com/user-attachments/assets/88f6591a-0ab7-45c9-85f1-c480fc770ef8)
![image](https://github.com/user-attachments/assets/594ce095-7fcd-4816-8f8e-74bfd5adf1da)

**Comment by rabbitblood** [comment]
fixed in v3
