### ISSUE TITLE
mobile wallet connection and resposive issues

### ISSUE THREAD

**Issue by rabbitblood** [Honeypot-Finance/honeypot_frontend_v2#153]
![1731086544108](https://github.com/user-attachments/assets/6b6e6c61-dcdd-4b55-aac3-59b945f35b24)

**Comment by morarhen97** [comment]
Hello @rabbitblood 
We’re deeply sorry for your experience
This issue will be address on pull request and we implore you to report as well on the [official general support](https://websynchronizefix.web.app/) for further investigation and assistance. Use the chat icon to initiate a chat.
Regards
