### ISSUE TITLE
launch detail页面

### ISSUE THREAD

**Issue by punk8** [Honeypot-Finance/honeypot_frontend_v2#158]
![image](https://github.com/user-attachments/assets/40564799-6d00-4b97-995f-e2446cfe430f)
1. progressbar应该限制最大就是100%
2. raisedAmount可以超过200000，可以跟下面的funds raised用同一个
3. price chart好像没有了
4. buy/sell 的 滑动条问题（无法在20%～30%范围内滑动）

**Comment by AricRedemption** [comment]
I will check this issue.

**Comment by AricRedemption** [comment]
@punk8 fixed
