### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by realTaki** [Honeypot-Finance/honeypot_frontend_v2#2]
<img width="196" alt="image" src="https://github.com/Honeypot-Finance/honeypot_frontend_v2/assets/21310549/99d34f40-20e6-4119-b6c1-ac57510561a4">

https://app.honeypotfinance.xyz/launch-detail/0xE22487E38aFD60189A0Ef7855FC0fB6983020dD2

display error at the "Token Raised" field when going to the detail page "View the Token"

**Comment by rabbitblood** [comment]
display fixed
