### ISSUE TITLE
Graph of price

### ISSUE THREAD

**Issue by realTaki** [Honeypot-Finance/honeypot_frontend_v2#28]
The current token price is listed on a separate page, which seems to be useless. Please refer to SyncSwap and click on the left side of the page to open the graph.

<img width="654" alt="image" src="https://github.com/user-attachments/assets/99ca6492-fe9e-42c1-884e-62e2b3ce504c">

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/2e7cfb4b-8bb1-458e-a532-4dfcd477f58a">

**Comment by rabbitblood** [comment]
implemented
