### ISSUE TITLE
display error when adding LP

### ISSUE THREAD

**Issue by realTaki** [Honeypot-Finance/honeypot_frontend_v2#30]
<img width="601" alt="image" src="https://github.com/user-attachments/assets/346bde5e-09b4-42d3-b8ee-36e7e7ed6ada">

display error when adding LP, it shows "create LP"

**Comment by rabbitblood** [comment]
![image](https://github.com/user-attachments/assets/069429f5-6792-4693-9d87-663e2a736112)
updated to Add Lp
