### ISSUE TITLE
align the token list with BEX

### ISSUE THREAD

**Issue by realTaki** [Honeypot-Finance/honeypot_frontend_v2#4]
https://bartio.bex.berachain.com/swap

Please align the token list with Berachain BEX. In general, we keep:
1. Test tokens from the launchpad
2. HPOT test tokens
3. Berachain native tokens
4. If any cooperating project wants to list their tokens, I will expand this list in the comments section in a timely manner.

**Comment by realTaki** [comment]
bArtio Testnet
Bera GasCoin
HONEY 0x0E4aaF1351de4c0264C5c7056Ef3777b41BD8e03
WBera 0x7507c1dc16935B82698e4C63f2746A2fCf994dF8
USDC 0xd6D83aF58a19Cd14eF3CF6fe848C9A4d21e5727c
WBTC 0x286F1C3f0323dB9c91D1E8f45c8DF2d065AB5fae
WETH 0x6E1E9896e93F7A71ECB33d4386b49DeeD67a231A
DAI 0x806Ef538b228844c73E8E692ADCFa8Eb2fCF729c
USDT 0x05D0dD5135E3eF3aDE32a9eF9Cb06e8D37A6795D

**Comment by rabbitblood** [comment]
so far we are aligned with tokens listed above, reopen this issue when more need to add more tokens
