### ISSUE TITLE
Price calculation error

### ISSUE THREAD

**Issue by realTaki** [Honeypot-Finance/honeypot_frontend_v2#5]
<img width="649" alt="image" src="https://github.com/Honeypot-Finance/honeypot_frontend_v2/assets/21310549/048f5c37-d30e-46aa-8424-c857631ba0f8">
---
<img width="728" alt="image" src="https://github.com/Honeypot-Finance/honeypot_frontend_v2/assets/21310549/c05f5606-ba7c-4ea5-93c9-dfbd103c4a7c">
---
Price calculation error.

**Comment by realTaki** [comment]
<img width="640" alt="image" src="https://github.com/Honeypot-Finance/honeypot_frontend_v2/assets/21310549/41c64a14-c2d9-4d5b-945d-d2884448a005">
 the same thing happened on "Add LP"

**Comment by zongzheng123** [comment]
Fixed @realTaki
