### ISSUE TITLE
bera兑换wbera

### ISSUE THREAD

**Issue by punk8** [Honeypot-Finance/honeypot_frontend_v2#83]
![image](https://github.com/user-attachments/assets/7007c10d-e048-4a02-b4c5-a6e7a6205914)
这个钱包bera只有1.07，但是在我们的dex里展示是5.039，实际上5.039是wbera的，其次我看了下uniswap，针对eth/weth的兑换是特殊处理的，现在我们反而是绕了一层
参考uniswap调用weth的deposit方法跟withdraw方法
![image](https://github.com/user-attachments/assets/b67cd866-a36e-4f1b-a34a-554db8998b60)

**Comment by bradstevens1** [comment]
Hello @punk8 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Uniswap live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
